name: granddevoir
description: Une application Flutter simple pour la gestion des dépenses

# Ne change pas ceci si tu ne sais pas ce que tu fais
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
